[server]
maxUploadSize = 50

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#334155"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8fafc"
textColor = "#0f172a"
font = "sans serif"
